
const types = {
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_POPULAR_DEALS: 'GET_POPULAR_DEALS',
    SHOPPING_CART: 'SHOPPING_CART',
    CATEGORY_SEARCHING: 'CATEGORY_SEARCHING',
    GET_PRODUCT_BY_CATEGORY_ID: 'GET_PRODUCT_BY_CATEGORY_ID',
    CLEAR_PRODUCT_BY_CATEGORY_ID: 'CLEAR_PRODUCT_BY_CATEGORY_ID',
    CART_ITEM_INCREASE:'CART_ITEM_INCREASE',
    CART_ITEM_DECREASE:'CART_ITEM_DECREASE',
    CLEAR_SHOPPING_CART:'CLEAR_SHOPPING_CART',

};

export default types;